---
- name: Ensure node_exporter user
  user:
    name: node_exporter
    shell: /usr/sbin/nologin
    system: yes

- name: Download node_exporter archive
  get_url:
    url: "https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz"
    dest: "/tmp/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz"
    mode: '0644'

- name: Extract node_exporter
  unarchive:
    src: "/tmp/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz"
    dest: "/tmp"
    remote_src: yes

- name: Install node_exporter binary
  copy:
    src: "/tmp/node_exporter-{{ node_exporter_version }}.linux-amd64/node_exporter"
    dest: "/usr/local/bin/node_exporter"
    mode: '0755'

- name: Create textfile collector dir
  file:
    path: "/var/lib/node_exporter/textfile"
    state: directory
    owner: node_exporter
    group: node_exporter
    mode: '0755'

- name: Install systemd service
  copy:
    src: "node_exporter.service"
    dest: "/etc/systemd/system/node_exporter.service"
    mode: '0644'

- name: Enable and start node_exporter
  systemd:
    name: node_exporter
    state: started
    enabled: yes
    daemon_reload: yes
