---
- name: Ensure Prometheus user exists
  ansible.builtin.user:
    name: prometheus
    shell: /usr/sbin/nologin
    system: true

- name: Create Prometheus directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: prometheus
    group: prometheus
    mode: "0755"
  loop:
    - /etc/prometheus
    - /var/lib/prometheus

- name: Download Prometheus archive
  ansible.builtin.get_url:
    url: >-
      https://github.com/prometheus/prometheus/releases/download/v{{ prometheus_version }}/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz
    dest: "/tmp/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz"
    mode: "0644"

- name: Extract Prometheus
  ansible.builtin.unarchive:
    src: "/tmp/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz"
    dest: "/tmp"
    remote_src: true

- name: Install Prometheus binaries
  ansible.builtin.copy:
    src: "/tmp/prometheus-{{ prometheus_version }}.linux-amd64/{{ item }}"
    dest: "/usr/local/bin/{{ item }}"
    mode: "0755"
  loop:
    - prometheus
    - promtool

- name: Install Prometheus consoles
  ansible.builtin.copy:
    src: "/tmp/prometheus-{{ prometheus_version }}.linux-amd64/{{ item }}"
    dest: "/etc/prometheus/{{ item }}"
    owner: prometheus
    group: prometheus
    mode: "0755"
  loop:
    - consoles
    - console_libraries

- name: Deploy prometheus.yml
  ansible.builtin.copy:
    src: "prometheus.yml"
    dest: "{{ prometheus_config_path }}"
    owner: prometheus
    group: prometheus
    mode: "0644"

- name: Install systemd service for Prometheus
  ansible.builtin.copy:
    src: "prometheus.service"
    dest: "/etc/systemd/system/prometheus.service"
    mode: "0644"

- name: Enable and start Prometheus
  ansible.builtin.systemd:
    name: prometheus
    state: started
    enabled: true
    daemon_reload: true
