# ansible/playbook.yml
---
- name: Deploy monitoring stack
  hosts: all
  become: yes
  gather_facts: false

  vars_files:
    - vars/main.yml

  roles:
    - role: prometheus
      when: inventory_hostname in groups.get('prometheus_server', [])
    - role: node_exporter
      when: inventory_hostname in groups.get('node_exporter_servers', []) or
            inventory_hostname in groups.get('prometheus_server', [])
    - role: docker_metrics
      when: inventory_hostname in groups.get('docker_metrics_servers', [])
    - role: watchdogs
      when: inventory_hostname in groups.get('node_exporter_servers', []) or
            inventory_hostname in groups.get('prometheus_server', [])
