name: Ansible CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ansible-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Ansible & Ansible Lint
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible ansible-lint

      - name: Show inventory (debug)
        run: |
          ansible-inventory -i ansible/hosts --list

      - name: Syntax check
        run: |
          ansible-playbook ansible/playbook.yml \
            --syntax-check \
            -i ansible/hosts

      - name: Lint check
        run: ansible-lint ansible/playbook.yml

      - name: Dry-run (limit to localhost so it never touches real hosts)
        run: |
          ansible-playbook ansible/playbook.yml \
            --check \
            -i ansible/hosts \
            -l localhost
