name: Ansible CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  ansible-syntax-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Ansible
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible

      - name: Ansible syntax check
        run: |
          ansible-playbook *.yml --syntax-check

      - name: Install ansible-lint
        run: |
          pip install ansible-lint

      - name: Run ansible-lint
        run: ansible-lint playbook.yml
